steps:
  - name: node
    entrypoint: npm
    args: ["run", "test"]

  # Build the container image
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest",
        "--build-arg",
        "DB_CONNECT=${_DB_CONNECT}",
        "--build-arg",
        "GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}",
        "--build-arg",
        "GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}",
        "--build-arg",
        "PASSPORT_SECRET=${_PASSPORT_SECRET}",
        "--build-arg",
        "SOCKET_ORIGIN=${_SOCKET_ORIGIN}",
        "--build-arg",
        "SERVER_URI=${_SERVER_URI}",
        "./back-end/",
      ]
    id: Building the container image
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}"]
    id: Pushing the image to registry
